#include "gtest/gtest.h"
#include "pstypes.h"
#include <cstring>

#define GAME_INTERFACE 0
#define GAME_OPTIONS_INTERFACE 1
#define GAME_PAUSE_INTERFACE 2
#define GAME_HELP_INTERFACE 3
#define GAME_BUDDY_INTERFACE 4
#define GAME_TELCOM_BRIEFINGS 5
#define GAME_TELCOM_AUTOMAP 6
#define GAME_TELCOM_CARGO 7
#define GAME_EXIT_CONFIRM 8
#define GAME_DLL_INTERFACE 9
#define GAME_SAVE_INTERFACE 10
#define GAME_LOAD_INTERFACE 11
#define GAME_TOGGLE_DEMO 12
#define GAME_POST_DEMO 13
#define GAME_DEMO_LOOP 14
#define GAME_LEVEL_WARP 15
#define GAME_DEBUGGRAPH_INTERFACE 16
#define GAMESAVE_SLOTS 8
#define GAMESAVE_DESCLEN 31
#define GAMESAVE_VERSION 2
#define GAMESAVE_OLDVER 0
#define LGS_OK 0
#define LGS_FILENOTFOUND 1
#define LGS_OUTDATEDVER 2
#define LGS_STARTLVLFAILED 3
#define LGS_MISSIONFAILED 4
#define LGS_OBJECTSCORRUPT 5
#define LGS_CORRUPTLEVEL 6
#define LEVEL_FILE_VERSION 132
#define LEVEL_FILE_OLDEST_COMPATIBLE_VERSION 13
#define CHUNK_TEXTURE_NAMES "TXNM"
#define CHUNK_ROOMS "ROOM"
#define CHUNK_OBJECTS "OBJS"
#define CHUNK_TERRAIN "TERR"
#define CHUNK_TRIGGERS "TRIG"
#define CHUNK_LIGHTMAPS "LMAP"
#define CHUNK_LEVEL_INFO "INFO"

TEST(GameSequenceConstantsTest, GameInterfaces) {
    EXPECT_EQ(GAME_INTERFACE, 0);
    EXPECT_EQ(GAME_OPTIONS_INTERFACE, 1);
    EXPECT_EQ(GAME_PAUSE_INTERFACE, 2);
    EXPECT_EQ(GAME_HELP_INTERFACE, 3);
    EXPECT_EQ(GAME_BUDDY_INTERFACE, 4);
    EXPECT_EQ(GAME_TELCOM_BRIEFINGS, 5);
    EXPECT_EQ(GAME_TELCOM_AUTOMAP, 6);
    EXPECT_EQ(GAME_TELCOM_CARGO, 7);
    EXPECT_EQ(GAME_EXIT_CONFIRM, 8);
    EXPECT_EQ(GAME_DLL_INTERFACE, 9);
    EXPECT_EQ(GAME_SAVE_INTERFACE, 10);
    EXPECT_EQ(GAME_LOAD_INTERFACE, 11);
    EXPECT_EQ(GAME_TOGGLE_DEMO, 12);
    EXPECT_EQ(GAME_POST_DEMO, 13);
    EXPECT_EQ(GAME_DEMO_LOOP, 14);
    EXPECT_EQ(GAME_LEVEL_WARP, 15);
    EXPECT_EQ(GAME_DEBUGGRAPH_INTERFACE, 16);
}

TEST(GameSequenceConstantsTest, InterfacesSequential) {
    EXPECT_EQ(GAME_DEBUGGRAPH_INTERFACE - GAME_INTERFACE, 16);
}

TEST(GameSaveConstantsTest, MaxSaveSlots) {
    EXPECT_EQ(GAMESAVE_SLOTS, 8);
    EXPECT_GT(GAMESAVE_SLOTS, 0);
}

TEST(GameSaveConstantsTest, DescriptionLength) {
    EXPECT_EQ(GAMESAVE_DESCLEN, 31);
    EXPECT_GT(GAMESAVE_DESCLEN, 0);
}

TEST(GameSaveConstantsTest, SaveVersion) {
    EXPECT_EQ(GAMESAVE_VERSION, 2);
    EXPECT_EQ(GAMESAVE_OLDVER, 0);
    EXPECT_LT(GAMESAVE_OLDVER, GAMESAVE_VERSION);
}

TEST(GameSaveConstantsTest, LoadGameStatus) {
    EXPECT_EQ(LGS_OK, 0);
    EXPECT_EQ(LGS_FILENOTFOUND, 1);
    EXPECT_EQ(LGS_OUTDATEDVER, 2);
    EXPECT_EQ(LGS_STARTLVLFAILED, 3);
    EXPECT_EQ(LGS_MISSIONFAILED, 4);
    EXPECT_EQ(LGS_OBJECTSCORRUPT, 5);
    EXPECT_EQ(LGS_CORRUPTLEVEL, 6);
}

TEST(GameSaveConstantsTest, LoadGameStatusSequential) {
    EXPECT_EQ(LGS_CORRUPTLEVEL - LGS_OK, 6);
}

TEST(LoadLevelConstantsTest, LevelFileVersion) {
    EXPECT_EQ(LEVEL_FILE_VERSION, 132);
    EXPECT_GT(LEVEL_FILE_VERSION, 0);
}

TEST(LoadLevelConstantsTest, LevelFileOldestCompatible) {
    EXPECT_EQ(LEVEL_FILE_OLDEST_COMPATIBLE_VERSION, 13);
    EXPECT_LT(LEVEL_FILE_OLDEST_COMPATIBLE_VERSION, LEVEL_FILE_VERSION);
}

TEST(LoadLevelConstantsTest, ChunkIdentifiers) {
    EXPECT_STREQ(CHUNK_TEXTURE_NAMES, "TXNM");
    EXPECT_STREQ(CHUNK_ROOMS, "ROOM");
    EXPECT_STREQ(CHUNK_OBJECTS, "OBJS");
    EXPECT_STREQ(CHUNK_TERRAIN, "TERR");
    EXPECT_STREQ(CHUNK_TRIGGERS, "TRIG");
    EXPECT_STREQ(CHUNK_LIGHTMAPS, "LMAP");
    EXPECT_STREQ(CHUNK_LEVEL_INFO, "INFO");
}

TEST(LoadLevelConstantsTest, ChunkNamesLength) {
    EXPECT_EQ(strlen(CHUNK_TEXTURE_NAMES), 4);
    EXPECT_EQ(strlen(CHUNK_ROOMS), 4);
    EXPECT_EQ(strlen(CHUNK_LEVEL_INFO), 4);
}

int main(int argc, char **argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
