#include "gtest/gtest.h"
#include "pstypes.h"
#include <cstring>

#define AMBIENT_FILE_NAME "ambient.dat"
#define MAX_LIGHT 1.0
#define LIGHTMAP_SPACING 5.0
#define VOLUME_SPACING 10.0
#define INVISIBLE_VOLUME_ELEMENT 0x01
#define MAX_SPECULAR_INCREMENTS 4096
#define MAX_POWERUPS 100
#define MAX_STATIC_POWERUPS 50
#define PF_IMAGE_BITMAP 1
#define POW_SHIELD 0
#define POW_ENERGY 1
#define POW_LASER 2
#define POW_VULCAN_WEAPON 3
#define POW_SUPER_LASER 7
#define POW_MISSILE_1 12
#define POW_MISSILE_4 13
#define POW_HOMING_MISSILE_1 14
#define POW_HOMING_MISSILE_4 15
#define POW_PROXIMITY_WEAPON 16
#define POW_SMART_MISSILE_WEAPON 17
#define POW_MEGA_WEAPON 18
#define POW_FLASH_MISSILE_1 19
#define POW_FLASH_MISSILE_4 20
#define POW_GUIDED_MISSILE_1 21
#define POW_GUIDED_MISSILE_4 22
#define POW_SMART_MINE 23
#define POW_MERCURY_MISSILE_1 24
#define POW_MERCURY_MISSILE_4 25
#define POW_EARTHSHAKER_MISSILE 26
#define POW_EXTRA_LIFE 27
#define POW_QUAD_FIRE 28
#define POW_VULCAN_AMMO 29
#define POW_CLOAK 30
#define POW_TURBO 31
#define POW_INVULNERABILITY 32
#define POW_FULL_MAP 33
#define POW_CONVERTER 34
#define POW_AMMO_RACK 35
#define POW_AFTERBURNER 36
#define POW_HEADLIGHT 37
#define POW_FLAG_BLUE 38
#define POW_FLAG_RED 39
#define POW_HOARD_ORB 40
#define MAX_POWERUP_SOUNDS 7
#define MAX_MARKER_MESSAGE_LENGTH 40

TEST(AmbientConstantsTest, AmbientFileName) {
    EXPECT_STREQ(AMBIENT_FILE_NAME, "ambient.dat");
}

TEST(LightingConstantsTest, MaxLight) {
    EXPECT_EQ(MAX_LIGHT, 1.0);
    EXPECT_GT(MAX_LIGHT, 0.0);
}

TEST(LightingConstantsTest, LightmapSpacing) {
    EXPECT_EQ(LIGHTMAP_SPACING, 5.0);
    EXPECT_GT(LIGHTMAP_SPACING, 0.0);
}

TEST(LightingConstantsTest, VolumeSpacing) {
    EXPECT_EQ(VOLUME_SPACING, 10.0);
    EXPECT_GT(VOLUME_SPACING, 0.0);
}

TEST(LightingConstantsTest, InvisibleVolumeElement) {
    EXPECT_EQ(INVISIBLE_VOLUME_ELEMENT, 0x01);
}

TEST(LightingConstantsTest, MaxSpecularIncrements) {
    EXPECT_EQ(MAX_SPECULAR_INCREMENTS, 4096);
    EXPECT_GT(MAX_SPECULAR_INCREMENTS, 0);
}

TEST(PowerupConstantsTest, MaxPowerups) {
    EXPECT_EQ(MAX_POWERUPS, 100);
    EXPECT_GT(MAX_POWERUPS, 0);
}

TEST(PowerupConstantsTest, MaxStaticPowerups) {
    EXPECT_EQ(MAX_STATIC_POWERUPS, 50);
    EXPECT_GT(MAX_STATIC_POWERUPS, 0);
}

TEST(PowerupConstantsTest, PowerupFeatureFlags) {
    EXPECT_EQ(PF_IMAGE_BITMAP, 1);
}

TEST(PowerupConstantsTest, PowerupIndicesBasic) {
    EXPECT_EQ(POW_SHIELD, 0);
    EXPECT_EQ(POW_ENERGY, 1);
    EXPECT_EQ(POW_LASER, 2);
    EXPECT_EQ(POW_VULCAN_WEAPON, 3);
    EXPECT_EQ(POW_SUPER_LASER, 7);
    EXPECT_EQ(POW_EXTRA_LIFE, 27);
    EXPECT_EQ(POW_QUAD_FIRE, 28);
    EXPECT_EQ(POW_VULCAN_AMMO, 29);
    EXPECT_EQ(POW_CLOAK, 30);
    EXPECT_EQ(POW_TURBO, 31);
    EXPECT_EQ(POW_INVULNERABILITY, 32);
    EXPECT_EQ(POW_FULL_MAP, 33);
    EXPECT_EQ(POW_CONVERTER, 34);
    EXPECT_EQ(POW_AMMO_RACK, 35);
    EXPECT_EQ(POW_AFTERBURNER, 36);
    EXPECT_EQ(POW_HEADLIGHT, 37);
}

TEST(PowerupConstantsTest, PowerupIndicesMissiles) {
    EXPECT_EQ(POW_MISSILE_1, 12);
    EXPECT_EQ(POW_MISSILE_4, 13);
    EXPECT_EQ(POW_HOMING_MISSILE_1, 14);
    EXPECT_EQ(POW_HOMING_MISSILE_4, 15);
    EXPECT_EQ(POW_PROXIMITY_WEAPON, 16);
    EXPECT_EQ(POW_SMART_MISSILE_WEAPON, 17);
    EXPECT_EQ(POW_MEGA_WEAPON, 18);
    EXPECT_EQ(POW_FLASH_MISSILE_1, 19);
    EXPECT_EQ(POW_FLASH_MISSILE_4, 20);
    EXPECT_EQ(POW_GUIDED_MISSILE_1, 21);
    EXPECT_EQ(POW_GUIDED_MISSILE_4, 22);
    EXPECT_EQ(POW_SMART_MINE, 23);
    EXPECT_EQ(POW_MERCURY_MISSILE_1, 24);
    EXPECT_EQ(POW_MERCURY_MISSILE_4, 25);
    EXPECT_EQ(POW_EARTHSHAKER_MISSILE, 26);
}

TEST(PowerupConstantsTest, PowerupIndicesMultiplayer) {
    EXPECT_EQ(POW_FLAG_BLUE, 38);
    EXPECT_EQ(POW_FLAG_RED, 39);
    EXPECT_EQ(POW_HOARD_ORB, 40);
}

TEST(PowerupConstantsTest, MaxPowerupSounds) {
    EXPECT_EQ(MAX_POWERUP_SOUNDS, 7);
    EXPECT_GT(MAX_POWERUP_SOUNDS, 0);
}

TEST(MarkerConstantsTest, MaxMarkerMessageLength) {
    EXPECT_EQ(MAX_MARKER_MESSAGE_LENGTH, 40);
    EXPECT_GT(MAX_MARKER_MESSAGE_LENGTH, 0);
}

TEST(MarkerConstantsTest, MarkerMessageLength_Reasonable) {
    EXPECT_LT(MAX_MARKER_MESSAGE_LENGTH, 256);
}

int main(int argc, char **argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
