#include "gtest/gtest.h"
#include "pstypes.h"

#define PARTICLE_LIFE 0.5
#define DEBRIS_LIFE 2.0
#define FF_MOVES 1
#define VISUAL_FIREBALL 0
#define REAL_FIREBALL 1
#define FIREBALL_ALPHA 0.9f
#define SMOKE_ALPHA 0.3f
#define MAX_FIREBALL_SIZE 80.0
#define DAMAGE_RING_TIME 1.5f
#define NUM_FIREBALLS 52
#define SF_FORCEUPDATE 0x01
#define SF_UPDATEDFORFRAME 0x02
#define SF_UPDATEEVERYFRAME 0x04
#define SPEW_RAND_WIGGLE 1
#define SPEW_RAND_SPEED 2
#define SPEW_RAND_SIZE 4
#define SPEW_RAND_SLIDE 8
#define SPEW_RAND_LIFETIME 16
#define MAX_SPEW_EFFECTS 50
#define MAX_MATCENS 60
#define MAX_MATCEN_NAME_LEN 32
#define MATCEN_LOADSAVE_VERSION 3
#define MAX_MATCEN_ALIVE_CHILDREN 32
#define MATCEN_OUTSIDE_NEAR_DIST 150.0f
#define MATCEN_ACTIVE_CHECK_RATE 4.0f
#define MATCEN_ACTIVE_CHECK_VARIENCE 1.0f
#define CHECK_ACTIVE_RATE 3.0f
#define CHECK_ACTIVE_VARIENCE 1.0f
#define MAX_MATCEN_EFFECT_SATURATION 2

TEST(FireballConstantsTest, ParticleLife) {
    EXPECT_EQ(PARTICLE_LIFE, 0.5);
    EXPECT_GT(PARTICLE_LIFE, 0.0);
}

TEST(FireballConstantsTest, DebrisLife) {
    EXPECT_EQ(DEBRIS_LIFE, 2.0);
    EXPECT_GT(DEBRIS_LIFE, 0.0);
}

TEST(FireballConstantsTest, FireballFlags) {
    EXPECT_EQ(FF_MOVES, 1);
}

TEST(FireballConstantsTest, FireballTypes) {
    EXPECT_EQ(VISUAL_FIREBALL, 0);
    EXPECT_EQ(REAL_FIREBALL, 1);
}

TEST(FireballConstantsTest, AlphaValues) {
    EXPECT_EQ(FIREBALL_ALPHA, 0.9f);
    EXPECT_EQ(SMOKE_ALPHA, 0.3f);
    EXPECT_GT(FIREBALL_ALPHA, SMOKE_ALPHA);
}

TEST(FireballConstantsTest, MaxFireballSize) {
    EXPECT_EQ(MAX_FIREBALL_SIZE, 80.0);
    EXPECT_GT(MAX_FIREBALL_SIZE, 0.0);
}

TEST(FireballConstantsTest, DamageRingTime) {
    EXPECT_EQ(DAMAGE_RING_TIME, 1.5f);
    EXPECT_GT(DAMAGE_RING_TIME, 0.0f);
}

TEST(FireballConstantsTest, NumFireballs) {
    EXPECT_EQ(NUM_FIREBALLS, 52);
    EXPECT_GT(NUM_FIREBALLS, 0);
}

TEST(SpewConstantsTest, SpewFlags) {
    EXPECT_EQ(SF_FORCEUPDATE, 0x01);
    EXPECT_EQ(SF_UPDATEDFORFRAME, 0x02);
    EXPECT_EQ(SF_UPDATEEVERYFRAME, 0x04);
}

TEST(SpewConstantsTest, SpewRandomFlags) {
    EXPECT_EQ(SPEW_RAND_WIGGLE, 1);
    EXPECT_EQ(SPEW_RAND_SPEED, 2);
    EXPECT_EQ(SPEW_RAND_SIZE, 4);
    EXPECT_EQ(SPEW_RAND_SLIDE, 8);
    EXPECT_EQ(SPEW_RAND_LIFETIME, 16);
}

TEST(SpewConstantsTest, MaxSpewEffects) {
    EXPECT_EQ(MAX_SPEW_EFFECTS, 50);
    EXPECT_GT(MAX_SPEW_EFFECTS, 0);
}

TEST(MatcenConstantsTest, MaxMatcens) {
    EXPECT_EQ(MAX_MATCENS, 60);
    EXPECT_GT(MAX_MATCENS, 0);
}

TEST(MatcenConstantsTest, MaxMatcenNameLength) {
    EXPECT_EQ(MAX_MATCEN_NAME_LEN, 32);
    EXPECT_GT(MAX_MATCEN_NAME_LEN, 0);
}

TEST(MatcenConstantsTest, MatcenLoadSaveVersion) {
    EXPECT_EQ(MATCEN_LOADSAVE_VERSION, 3);
    EXPECT_GT(MATCEN_LOADSAVE_VERSION, 0);
}

TEST(MatcenConstantsTest, MaxMatcenAliveChildren) {
    EXPECT_EQ(MAX_MATCEN_ALIVE_CHILDREN, 32);
    EXPECT_GT(MAX_MATCEN_ALIVE_CHILDREN, 0);
}

TEST(MatcenConstantsTest, MatcenDistance) {
    EXPECT_EQ(MATCEN_OUTSIDE_NEAR_DIST, 150.0f);
    EXPECT_GT(MATCEN_OUTSIDE_NEAR_DIST, 0.0f);
}

TEST(MatcenConstantsTest, MatcenTiming) {
    EXPECT_EQ(MATCEN_ACTIVE_CHECK_RATE, 4.0f);
    EXPECT_EQ(MATCEN_ACTIVE_CHECK_VARIENCE, 1.0f);
    EXPECT_EQ(CHECK_ACTIVE_RATE, 3.0f);
    EXPECT_EQ(CHECK_ACTIVE_VARIENCE, 1.0f);
    EXPECT_GT(MATCEN_ACTIVE_CHECK_RATE, 0.0f);
}

TEST(MatcenConstantsTest, MaxMatcenEffectSaturation) {
    EXPECT_EQ(MAX_MATCEN_EFFECT_SATURATION, 2);
    EXPECT_GT(MAX_MATCEN_EFFECT_SATURATION, 0);
}

int main(int argc, char **argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
